# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  images:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v2

      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls */image.pkr.hcl | jq -R -s -c 'split("\n")[:-1]')"

  build:
    needs: images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: ${{ fromJson(needs.images.outputs.matrix) }}

    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.image }}

    steps:

      - uses: actions/checkout@v3

      - name: Using image definition
        run: echo ${{ matrix.image }}


