# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v3

      - name: Generate Image Matrix
        id: set-matrix
        run: echo "matrix=$(find . -type f -name 'image.pkr.hcl' | sed -r 's|/[^/]+$||' | sort -u | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  build:
    needs: build-matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.build-matrix.outputs.matrix) }}

    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.image }}

    steps:

      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Convert Image HCL to JSON
        run: |
          JSON2HCL_URL=$(curl --silent "https://api.github.com/repos/kvz/json2hcl/releases/latest" | jq --raw-output '.assets[].browser_download_url | select(contains("_linux_amd64.tar.gz"))')
          wget -qc $JSON2HCL_URL -O - | tar -xz -C $RUNNER_TEMP && chmod 755 $RUNNER_TEMP/json2hcl
          $RUNNER_TEMP/json2hcl -reverse < ./image.pkr.hcl | jq . > ./image.pkr.json
          cat ./image.pkr.json

      - name: Prepare Image Definition
        run: cp -f ${{ github.workspace }}/_core/*.pkr.hcl ./

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.8.7"

      - name: Init Packer
        run: packer init .

      - name: Build Image
        run: packer build -force -color=false -on-error=abort -timestamp-ui .